/*
    Copyright 2023 Terso Solutions, Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

using System.Collections.Generic;

namespace TersoSolutions.Jetstream.Sdk.Objects
{
    /// <summary>
    /// A data transfer object containing properties for alias information
    /// </summary>
    public class AliasDto
    {
        /// <summary>
        /// Autogenerated ID associated to the Alias
        /// </summary>
        public ulong Id { get; set; }

        /// <summary>
        /// The name of the Alias
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// List of devices associated to Alias
        /// </summary>
        public List<string> Devices { get; set; }

        /// <summary>
        /// Holds the region the alias is valid in 
        /// </summary>
        public string Region { get; set; }
    }
}
