using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace TersoSolutions.Jetstream.Sdk.Objects;

/// <summary>
/// Runtime detailed policies DTO for v3
/// </summary>
public class DetailedPoliciesDto
{
    /// <summary>
    /// Autogenerated Id for the policy
    /// </summary>
    public ulong Id { get; set; }

    /// <summary>
    /// The name of the policy
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Referenced name of the device definition to which the policy applies
    /// </summary>
    public string DeviceDefinition { get; set; }

    /// <summary>
    /// Configuration parameters and their values as described in a device definition.
    /// </summary>
    /// <remarks>
    /// Validate with Extensions.ValidatePolicyDtoParameters, merging the ModelStateDictionary with the Model state in the calling method.
    /// </remarks>
    public Dictionary<string, string> Parameters { get; set; }

    /// <summary>
    /// List of devices for the policy
    /// </summary>
    public List<PolicyDevice> Devices { get; set; }
}

/// <summary>
/// Policy device subclass
/// </summary>
public class PolicyDevice
{
    /// <summary>
    /// Policy name
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Policy parameters
    /// </summary>
    public Dictionary<string, string> Parameters { get; set; }
}
