/*
    Copyright 2019 Terso Solutions, Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

using System.Collections.Generic;

namespace TersoSolutions.Jetstream.SDK.Objects.Events
{
    /// <summary>
    /// The Alias Modified Event is generated when an alias is updated using the PUT verb.
    /// </summary>
    public class AliasModifiedEventDto : EventDto
    {
        /// <summary>
        /// Autogenerated ID associated to the Alias
        /// </summary>
        public ulong Id { get; set; }

        /// <summary>
        /// Name of the alias modified
        /// </summary>
        public string Alias { get; set; }

        /// <summary>
        /// The updated list of devices
        /// that have this alias available
        /// </summary>
        public List<string> Devices { get; set; }

        /// <summary>
        /// Region the alias was added to
        /// </summary>
        public string Region { get; set; }
    }
}
