/*
    Copyright 2019 Terso Solutions, Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

using System.Collections.Generic;

namespace TersoSolutions.Jetstream.SDK.Objects.Events
{
    /// <summary>
    /// The Device Credential Modified Event is generated by Jetstream
    /// when a device's credentials are updated.
    /// </summary>
    public class DeviceCredentialsModifiedEventDto : EventDto
    {
        // Current state of valid credentials for the device
        public List<string> CurrentCredentials { get; set; }

        /// <summary>
        /// The type of the credentials modified
        /// </summary>
        public string CredentialType { get; set; }

        // The device whose credentials were changed
        public string Device { get; set; }
    }
}
