/*
    Copyright 2019 Terso Solutions, Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

using System.Collections.Generic;

namespace TersoSolutions.Jetstream.SDK.Objects.Events
{
    /// <summary>
    /// The Device Credential Added Event is generated by Jetstream
    /// when a new credential is assigned to a device.
    /// </summary>
    public class DeviceCredentialsAddedEventDto : EventDto
    {
        // List of credentials added
        public List<string> AddedCredentials { get; set; }

        /// <summary>
        /// The type of the credentials added
        /// </summary>
        public string CredentialType { get; set; }

        // The device whose credentials were changed
        public string Device { get; set; }
    }
}
