/*
    Copyright 2019 Terso Solutions, Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

using System.Collections.Generic;

namespace TersoSolutions.Jetstream.Sdk.Objects.Events
{
    /// <summary>
    /// The BusinessProcessEvents is generated by a device, and it can contain any type of data that the device
    /// wants to send to the users.
    /// </summary>
    public class BusinessProcessEventDto : DeviceEventDto
    {
        /// <summary>
        /// The type of process that this event relates to.
        /// </summary>
        public string ProcessType { get; set; }

        /// <summary>
        /// Any parameters that the device includes in the event.
        /// </summary>
        public List<KeyValuePair<string, string>> Parameters { get; set; }
    }
}
