/*
    Copyright 2023 Terso Solutions, Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

using System.Collections.Generic;

namespace TersoSolutions.Jetstream.Sdk.Objects.Events
{
    /// <summary>
    /// The Object Event is generated by a device when it performs a scan to retrieve all its inventory.
    /// </summary>
    public class ObjectEventDto : DeviceEventDto
    {
        /// <summary>
        /// EPCs observed by the device
        /// </summary>
        public IList<string> Observe { get; set; }

        /// <summary>
        /// The Alias used by the device, if any
        /// </summary>
        public string Alias { get; set; }

        /// <summary>
        /// The credential used by the user who triggered the object event, if any
        /// </summary>
        public string Credential { get; set; }
    }
}
